import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:8000/welcome');
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: 'Login' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('textbox', { name: 'Username atau No Induk' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('textbox', { name: 'Username atau No Induk' }).fill('admin');
  await page.waitForTimeout(1000);
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('textbox', { name: 'Password' }).fill('12345');
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: 'Login' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: 'OK' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: ' Laporan ' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: ' Verifikasi Laporan' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('row', { name: '1 Budi Hartono Gedung Teknik' }).getByRole('button').click();
  await page.waitForTimeout(1000);
  await page.locator('select[name="details[7][skor][C2]"]').selectOption('2');
  await page.waitForTimeout(1000);
  await page.locator('select[name="details[7][skor][C5]"]').selectOption('2');
  await page.waitForTimeout(1000);
  await page.locator('select[name="details[7][skor][C3]"]').selectOption('3');
  await page.waitForTimeout(1000);
  await page.locator('select[name="details[7][skor][C6]"]').selectOption('2');
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: ' Simpan Semua ' }).click();
});