import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:8000/welcome');
  await page.waitForTimeout(1500);
  await page.getByRole('link', { name: 'Login' }).click();
  await page.waitForTimeout(1500);
  await page.getByRole('textbox', { name: 'Username atau No Induk' }).click();
  await page.waitForTimeout(1500);
  await page.getByRole('textbox', { name: 'Username atau No Induk' }).fill('admin');
  await page.waitForTimeout(1500);
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.waitForTimeout(1500);
  await page.getByRole('textbox', { name: 'Password' }).fill('12345');
  await page.waitForTimeout(1500);
  await page.getByRole('button', { name: 'Login' }).click();
  await page.waitForTimeout(1500);
  await page.getByRole('button', { name: 'OK' }).click();
  await page.waitForTimeout(1500);
  await page.getByRole('link', { name: ' SPK & Kriteria ' }).click();
  await page.waitForTimeout(1500);
  await page.getByRole('link', { name: ' Prioritas Perbaikan' }).click();
  await page.waitForTimeout(1500);
  await page.getByRole('row', { name: '1 Layar Proyektor Rizky' }).getByRole('button').click();
  await page.waitForTimeout(1500);
  await page.getByLabel('Pilih Teknisi').selectOption('28');
  await page.waitForTimeout(1500);
  await page.getByRole('button', { name: ' Tugaskan' }).click();
  await page.waitForTimeout(1500);
});