import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('http://localhost:8000/welcome');
    await page.waitForTimeout(1000);
    await page.getByRole('link', { name: 'Login' }).click();
    await page.waitForTimeout(1000);
    await page.getByRole('textbox', { name: 'Username atau No Induk' }).click();
    await page.waitForTimeout(1000);
    await page.getByRole('textbox', { name: 'Username atau No Induk' }).fill('admin');
    await page.waitForTimeout(1000);
    await page.getByRole('textbox', { name: 'Password' }).click();
    await page.waitForTimeout(1000);
    await page.getByRole('textbox', { name: 'Password' }).fill('12345');
    await page.waitForTimeout(1000);
    await page.getByRole('button', { name: 'Login' }).click();
    await page.waitForTimeout(1000);
    await page.getByRole('button', { name: 'OK' }).click();
    await page.waitForTimeout(1000);
    await page.getByRole('link', { name: ' Master Data ' }).click();
    await page.waitForTimeout(1000);
    await page.getByRole('link', { name: ' Kategori Fasilitas' }).click();
    await page.waitForTimeout(1000);
    await page.getByRole('button', { name: 'Tambah Kategori Fasilitas' }).click();
    await page.waitForTimeout(1000);
    await page.locator('input[name="kode_kategori"]').click();
    await page.waitForTimeout(1000);
    await page.locator('input[name="kode_kategori"]').fill('LAB');
    await page.waitForTimeout(1000);
    await page.locator('input[name="nama_kategori"]').click();
    await page.waitForTimeout(1000);
    await page.locator('input[name="nama_kategori"]').fill('Testing');
    await page.waitForTimeout(1000);
    await page.getByRole('button', { name: 'Simpan' }).click();
    await page.waitForTimeout(1000);
});